../Verilog/RTL/alu.v
../Verilog/RTL/alu_control.v
../Verilog/RTL/branch_unit.v
../Verilog/RTL/control_unit.v
../Verilog/RTL/cpu.v
../Verilog/RTL/immediate_extend_unit.v
../Verilog/RTL/mux_2.v
../Verilog/RTL/pc.v
../Verilog/RTL/register_file.v
../Verilog/RTL/reg_arstn.v
../Verilog/RTL/reg_arstn_en.v
../Verilog/RTL/sram.v
../Verilog/cpu_tb.v
../Verilog/sky130_sram_2rw.v
